version: "3.9"

services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8093:8093"
    depends_on:
      - blog-db
    environment:
      HOST: blog-db
      PORT: 5432
      POSTGRES_DB: blog_service_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qwerty

  blog-db:
    image: postgres:17.2
    container_name: blog_db
    ports:
      - "5432:5432"
    volumes:
      - blog-service-data-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog_service_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/psqldata
    healthcheck:
      test: [ CMD-SHELL, pg_isready -U dev -d blog_service_db ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  blog-service-data-storage:
